-- Replace sample menu with full PDF menu (EN+AR, deduped)
-- Soft-delete existing categories/products and insert new catalog

update public.products
set is_deleted = true, is_active = false, updated_at = now()
where is_deleted = false;

update public.categories
set
  slug = slug || '_archived_' || replace(id::text, '-', ''),
  is_deleted = true,
  is_active = false,
  updated_at = now()
where is_deleted = false;

insert into public.categories (slug, name_en, name_ar, sort_order) values
  ('sides', 'SIDE DISHES', 'الأطباق الجانبية', 1),
  ('mains', 'MAIN DISHES', 'الأطباق الرئيسية', 2),
  ('royal', 'FAWZY ROYAL DISHES', 'أطباق فوزي الملكية', 3),
  ('soups', 'SOUPS', 'الشوربة', 4),
  ('salads', 'SALADS', 'السلطات', 5),
  ('appetizers', 'APPETIZERS', 'المقبلات', 6),
  ('grill-plates', 'GRILL PLATES', 'جريل', 7),
  ('sandwiches', 'SANDWICHES', 'السندوتشات', 8),
  ('desserts', 'DESSERTS', 'الحلو', 9),
  ('tajines', 'TAJINES', 'الطواجن', 10),
  ('hot-drinks', 'HOT DRINKS', 'المشروبات الساخنة', 11),
  ('cold-drinks', 'COLD DRINKS', 'المشروبات الباردة', 12),
  ('grills', 'GRILLS', 'المشويات', 13);

insert into public.products (
  category_id,
  name_en,
  name_ar,
  description_en,
  description_ar,
  price_en,
  price_ar,
  image_url,
  badge_en,
  badge_ar,
  tags,
  sort_order,
  is_signature,
  signature_sort_order
)
select
  c.id,
  v.name_en,
  v.name_ar,
  v.description_en,
  v.description_ar,
  v.price_en,
  v.price_ar,
  v.image_url,
  v.badge_en,
  v.badge_ar,
  '[]'::jsonb,
  v.sort_order,
  v.is_signature,
  v.signature_sort_order
from (
  values
    ('sides', 'Rice with Vermicelli', 'أرز بالشعرية', '', '', '62 EGP', '62 ج.م', 'images/menu/rice-with-vermicelli.jpg', null, null, 1, false, 0),
    ('sides', 'Plain Mixed Rice', 'أرز بالخلطة ساده', '', '', '65 EGP', '65 ج.م', 'images/menu/plain-mixed-rice.jpg', null, null, 2, false, 0),
    ('sides', 'Mixed Rice with Nuts and Liver', 'أرز بالخلطة مكسرات + كبده', '', '', '90 EGP', '90 ج.م', 'images/menu/mixed-rice-with-nuts-and-liver.jpg', null, null, 3, false, 0),
    ('sides', 'White Rice', 'أرز ابيض', '', '', '62 EGP', '62 ج.م', 'images/menu/white-rice.jpg', null, null, 4, false, 0),
    ('sides', 'Basmati Rice', 'أرز بسمتى', '', '', '65 EGP', '65 ج.م', 'images/menu/basmati-rice.jpg', null, null, 5, false, 0),
    ('sides', 'Spaghetti Red Sauce', 'مكرونة اسباجتى صوص أحمر', '', '', '105 EGP', '105 ج.م', 'images/menu/spaghetti-red-sauce.jpg', null, null, 6, false, 0),
    ('sides', 'Pasta White Sauce', 'مكرونة وايت صوص', '', '', '145 EGP', '145 ج.م', 'images/menu/pasta-white-sauce.jpg', null, null, 7, false, 0),
    ('sides', 'Pasta Bolognese', 'مكرونة صوص بولونيز', '', '', '205 EGP', '205 ج.م', 'images/menu/pasta-bolognese.jpg', null, null, 8, false, 0),
    ('sides', 'Negresco Pasta', 'مكرونة نجرسكو', '', '', '205 EGP', '205 ج.م', 'images/menu/negresco-pasta.jpg', null, null, 9, false, 0),
    ('sides', 'Oven Baked Pasta', 'مكرونة فرن', '', '', '205 EGP', '205 ج.م', 'images/menu/oven-baked-pasta.jpg', null, null, 10, false, 0),
    ('sides', 'French Fries', 'بوم فريت', '', '', '65 EGP', '65 ج.م', 'images/menu/french-fries.jpg', null, null, 11, false, 0),
    ('sides', 'Sautéed Vegetables', 'خضار سوتيه', '', '', '70 EGP', '70 ج.م', 'images/menu/sauteed-vegetables.jpg', null, null, 12, false, 0),
    ('sides', 'White Rice Bolognese', 'أرز ابيض بولونيز', '', '', '160 EGP', '160 ج.م', 'images/menu/white-rice-bolognese.jpg', null, null, 13, false, 0),
    ('sides', 'Plain Fattah', 'فتة سادة', '', '', '115 EGP', '115 ج.م', 'images/menu/plain-fattah.jpg', null, null, 14, false, 0),
    ('mains', 'Escalope Pane with Rice or Potatoes', 'إسكالوب بانية مع أرز أو بطاطس', '', '', '550 EGP', '550 ج.م', 'images/menu/escalope-pane-with-rice-or-potatoes.jpg', null, null, 1, false, 0),
    ('mains', 'Mushroom Piccata with Rice or Potatoes', 'بيكاتا مشروم مع أرز أو بطاطس', '', '', '550 EGP', '550 ج.م', 'images/menu/mushroom-piccata-with-rice-or-potatoes.jpg', null, null, 2, false, 0),
    ('mains', 'Chicken Pane with Rice or Potatoes', 'فراخ بانية مع أرز أو بطاطس', '', '', '400 EGP', '400 ج.م', 'images/menu/chicken-pane-with-rice-or-potatoes.jpg', null, null, 3, false, 0),
    ('mains', 'Fillet au Poivre with Rice or Potatoes', 'فيليه بوافر مع أرز أو بطاطس', '', '', '540 EGP', '540 ج.م', 'images/menu/fillet-au-poivre-with-rice-or-potatoes.jpg', null, null, 4, false, 0),
    ('mains', 'Lamb Shank Fattah', 'فتة موزة ضانى', '', '', '710 EGP', '710 ج.م', 'images/menu/lamb-shank-fattah.jpg', null, null, 5, false, 0),
    ('mains', 'Veal Shank with Vermicelli and Nuts', 'موزة بتلو بالشعرية والمكسرات', '', '', '725 EGP', '725 ج.م', 'images/menu/veal-shank-with-vermicelli-and-nuts.jpg', null, null, 6, false, 0),
    ('mains', 'Lamb Shank Tanjia with Vegetable Basmati', 'طنجية موزة ضانى + أرز بسمتى بالخضار', '', '', '745 EGP', '745 ج.م', 'images/menu/lamb-shank-tanjia-with-vegetable-basmati.jpg', null, null, 7, false, 0),
    ('mains', 'Half Duck Orange Sauce with Red Rice', '½ بطة بصوص البرتقال مع أرز أحمر', '', '', '540 EGP', '540 ج.م', 'images/menu/half-duck-orange-sauce-with-red-rice.jpg', null, null, 8, false, 0),
    ('royal', 'Royal Circassian', 'الشركسية الملكية', '', '', '650 EGP', '650 ج.م', 'images/menu/royal-circassian.jpg', null, null, 1, false, 0),
    ('royal', 'The Golden Pottery', 'الفخارة الذهبية', 'Pigeon, grape leaves, and pigeon rice', 'حمام + ورق عنب + أرز الحمام', '700 EGP', '700 ج.م', 'images/menu/the-golden-pottery.jpg', null, null, 2, false, 0),
    ('royal', '4G Kofta', 'كفتة 4G', 'Kofta with sweet and sour sauce', 'كفتة + صوص سويت أند ساور', '550 EGP', '550 ج.م', 'images/menu/4g-kofta.jpg', null, null, 3, false, 0),
    ('royal', 'Levantine Kofta', 'الكفتة الشامية', '', '', '550 EGP', '550 ج.م', 'images/menu/levantine-kofta.jpg', null, null, 4, false, 0),
    ('royal', 'The King''s Crown', 'تاج الملك', 'Kofta, lamb kebab, tarb, sausage, lamb chops, and shish tawook', 'كفتة + كباب ضاني + طرب + سجق + ريش ضاني + شيش طاووق', '2850 EGP', '2850 ج.م', 'images/menu/the-king-s-crown.jpg', null, null, 5, true, 1),
    ('royal', 'Lamb Shoulder Zend', 'زند ضاني', '', '', '2350 EGP', '2350 ج.م', 'images/menu/lamb-shoulder-zend.jpg', null, null, 6, false, 0),
    ('royal', 'The King''s Grill', 'شواية الملك', 'Kebab, kofta, tawook, and sausage', 'كباب + كفتة + طاووق + سجق', '1200 EGP', '1200 ج.م', 'images/menu/the-king-s-grill.jpg', null, null, 7, true, 2),
    ('soups', 'Fawzy Soup with Lamb Ribs', 'شوربة فوزي (ريش ضاني)', '', '', '230 EGP', '230 ج.م', 'images/menu/fawzy-soup-with-lamb-ribs.jpg', null, null, 1, false, 0),
    ('soups', 'Orzo Soup', 'شوربة لسان عصفور', '', '', '70 EGP', '70 ج.م', 'images/menu/orzo-soup.jpg', null, null, 2, false, 0),
    ('soups', 'Cream of Chicken Soup', 'شوربة فراخ بالكريمة', '', '', '85 EGP', '85 ج.م', 'images/menu/cream-of-chicken-soup.jpg', null, null, 3, false, 0),
    ('soups', 'Cream of Mushroom Soup', 'شوربة مشروم بالكريمة', '', '', '90 EGP', '90 ج.م', 'images/menu/cream-of-mushroom-soup.jpg', null, null, 4, false, 0),
    ('soups', 'Pigeon Soup', 'شوربة حمام', '', '', '65 EGP', '65 ج.م', 'images/menu/pigeon-soup.jpg', null, null, 5, false, 0),
    ('soups', 'Lentil Soup', 'شوربة عدس', '', '', '80 EGP', '80 ج.م', 'images/menu/lentil-soup.jpg', null, null, 6, false, 0),
    ('soups', 'Knuckle Soup', 'شوربة كوارع', '', '', '205 EGP', '205 ج.م', 'images/menu/knuckle-soup.jpg', null, null, 7, false, 0),
    ('salads', 'Green Salad', 'سلطة خضراء', '', '', '37 EGP', '37 ج.م', 'images/menu/green-salad.jpg', null, null, 1, false, 0),
    ('salads', 'Tahini', 'طحينة', '', '', '37 EGP', '37 ج.م', 'images/menu/tahini.jpg', null, null, 2, false, 0),
    ('salads', 'Baba Ganoush', 'بابا غنوج', '', '', '37 EGP', '37 ج.م', 'images/menu/baba-ganoush.jpg', null, null, 3, false, 0),
    ('salads', 'Cucumber Salad', 'خيار', '', '', '37 EGP', '37 ج.م', 'images/menu/cucumber-salad.jpg', null, null, 4, false, 0),
    ('salads', 'Eggplant Salad', 'باذنجان', '', '', '37 EGP', '37 ج.م', 'images/menu/eggplant-salad.jpg', null, null, 5, false, 0),
    ('salads', 'Garlic Dip Toum', 'ثومية', '', '', '45 EGP', '45 ج.م', 'images/menu/garlic-dip-toum.jpg', null, null, 6, false, 0),
    ('salads', 'Yogurt Salad', 'زبادي', '', '', '45 EGP', '45 ج.م', 'images/menu/yogurt-salad.jpg', null, null, 7, false, 0),
    ('salads', 'Marinated Tomatoes', 'طماطم متبلة', '', '', '37 EGP', '37 ج.م', 'images/menu/marinated-tomatoes.jpg', null, null, 8, false, 0),
    ('salads', 'Coleslaw', 'كول سلو', '', '', '45 EGP', '45 ج.م', 'images/menu/coleslaw.jpg', null, null, 9, false, 0),
    ('salads', 'Mixed Sliced Salads', 'ميكس سلاط شرائح', '', '', '75 EGP', '75 ج.م', 'images/menu/mixed-sliced-salads.jpg', null, null, 10, false, 0),
    ('salads', 'Pickles', 'مخلل', '', '', '37 EGP', '37 ج.م', 'images/menu/pickles.jpg', null, null, 11, false, 0),
    ('salads', 'Spicy Potatoes', 'بطاطس حارة', '', '', '45 EGP', '45 ج.م', 'images/menu/spicy-potatoes.jpg', null, null, 12, false, 0),
    ('salads', 'Beetroot Salad', 'سلطة بنجر', '', '', '45 EGP', '45 ج.م', 'images/menu/beetroot-salad.jpg', null, null, 13, false, 0),
    ('salads', 'Spicy Cheese', 'جبنه حارة', '', '', '45 EGP', '45 ج.م', 'images/menu/spicy-cheese.jpg', null, null, 14, false, 0),
    ('salads', 'Chicken Caesar Salad', 'سيزار سلاط بالفراخ', '', '', '145 EGP', '145 ج.م', 'images/menu/chicken-caesar-salad.jpg', null, null, 15, false, 0),
    ('salads', 'Arugula with Mushrooms', 'جرجير بالمشروم', '', '', '105 EGP', '105 ج.م', 'images/menu/arugula-with-mushrooms.jpg', null, null, 16, false, 0),
    ('salads', 'Fattoush', 'فتوش', '', '', '95 EGP', '95 ج.م', 'images/menu/fattoush.jpg', null, null, 17, false, 0),
    ('appetizers', 'Fawzy Appetizers Mixed Stuffed', 'مقبلات فوزى (محشى مشكل)', 'Cheese sambousek, meat sambousek, mombar, and sausage', 'سمبوسك جبنه + سمبوسك باللحم + ممبار + سجق', '405 EGP', '405 ج.م', 'images/menu/fawzy-appetizers-mixed-stuffed.jpg', null, null, 1, false, 0),
    ('appetizers', 'Mixed Stuffed Vegetables', 'محشى مشكل', '', '', '95 EGP', '95 ج.م', 'images/menu/mixed-stuffed-vegetables.jpg', null, null, 2, false, 0),
    ('appetizers', 'Stuffed Grape Leaves', 'محشى ورق عنب', '', '', '95 EGP', '95 ج.م', 'images/menu/stuffed-grape-leaves.jpg', null, null, 3, false, 0),
    ('appetizers', 'Stuffed Cabbage', 'محشى كرنب', '', '', '95 EGP', '95 ج.م', 'images/menu/stuffed-cabbage.jpg', null, null, 4, false, 0),
    ('appetizers', 'Meat Sambousek 4 Pieces', 'سمبوسك باللحمة 4 قطع', '', '', '84 EGP', '84 ج.م', 'images/menu/meat-sambousek-4-pieces.jpg', null, null, 5, false, 0),
    ('appetizers', 'Cheese Sambousek 4 Pieces', 'سمبوسك بالجبنة 4 قطع', '', '', '84 EGP', '84 ج.م', 'images/menu/cheese-sambousek-4-pieces.jpg', null, null, 6, false, 0),
    ('appetizers', 'Mombar', 'ممبار', '', '', '105 EGP', '105 ج.م', 'images/menu/mombar.jpg', null, null, 7, false, 0),
    ('appetizers', 'Sausage with Pomegranate Molasses', 'سجق دبس الرمان', '', '', '320 EGP', '320 ج.م', 'images/menu/sausage-with-pomegranate-molasses.jpg', null, null, 8, false, 0),
    ('appetizers', 'Roqaq with Minced Meat', 'رقاق باللحمة المفرومة', '', '', '220 EGP', '220 ج.م', 'images/menu/roqaq-with-minced-meat.jpg', null, null, 9, false, 0),
    ('appetizers', 'Bread Basket', 'سلة خبز', '', '', '30 EGP', '30 ج.م', 'images/menu/bread-basket.jpg', null, null, 10, false, 0),
    ('grill-plates', 'Meat Parcel', 'ورقة لحمة', '', '', '440 EGP', '440 ج.م', 'images/menu/meat-parcel.jpg', null, null, 1, false, 0),
    ('grill-plates', 'Liver Parcel', 'ورقة كبدة', '', '', '400 EGP', '400 ج.م', 'images/menu/liver-parcel.jpg', null, null, 2, false, 0),
    ('grill-plates', 'Sausage Parcel', 'ورقة سجق', '', '', '380 EGP', '380 ج.م', 'images/menu/sausage-parcel.jpg', null, null, 3, false, 0),
    ('grill-plates', 'Grilled Liver and Kidneys Parcel', 'ورقة كبده وكلاوى جريل', '', '', '370 EGP', '370 ج.م', 'images/menu/grilled-liver-and-kidneys-parcel.jpg', null, null, 4, false, 0),
    ('grill-plates', 'Grilled Offal Parcel', 'ورقة مخاصى جريل', '', '', '370 EGP', '370 ج.م', 'images/menu/grilled-offal-parcel.jpg', null, null, 5, false, 0),
    ('grill-plates', 'Chicken Fajita', 'فاهيتا فراخ', '', '', '350 EGP', '350 ج.م', 'images/menu/chicken-fajita.jpg', null, null, 6, false, 0),
    ('grill-plates', 'Sausage Fried with Lamb Fat', 'سجق محمر بالليه', '', '', '350 EGP', '350 ج.م', 'images/menu/sausage-fried-with-lamb-fat.jpg', null, null, 7, false, 0),
    ('grill-plates', 'Liver Fried with Lamb Fat', 'كبده محمره بالليه', '', '', '350 EGP', '350 ج.م', 'images/menu/liver-fried-with-lamb-fat.jpg', null, null, 8, false, 0),
    ('grill-plates', 'Fawzy Grill Parcel', 'ورقة فوزى جريل', 'Kidneys, liver, and offal', 'كلاوى + كبدة + مخاصى', '380 EGP', '380 ج.م', 'images/menu/fawzy-grill-parcel.jpg', null, null, 9, false, 0),
    ('sandwiches', 'Kofta Sandwich', 'سندوتش كفتة', '', '', '150 EGP', '150 ج.م', 'images/menu/kofta-sandwich.jpg', null, null, 1, false, 0),
    ('sandwiches', 'Tarb Sandwich', 'سندوتش طرب', '', '', '200 EGP', '200 ج.م', 'images/menu/tarb-sandwich.jpg', null, null, 2, false, 0),
    ('sandwiches', 'Veal Kebab Sandwich', 'سندوتش كباب بتلو', '', '', '200 EGP', '200 ج.م', 'images/menu/veal-kebab-sandwich.jpg', null, null, 3, false, 0),
    ('sandwiches', 'Lamb Kebab Sandwich', 'سندوتش كباب ضانى', '', '', '200 EGP', '200 ج.م', 'images/menu/lamb-kebab-sandwich.jpg', null, null, 4, false, 0),
    ('sandwiches', 'Sausage Sandwich', 'سندوتش سجق', '', '', '150 EGP', '150 ج.م', 'images/menu/sausage-sandwich.jpg', null, null, 5, false, 0),
    ('sandwiches', 'Tawook Sandwich', 'سندوتش طاووق', '', '', '98 EGP', '98 ج.م', 'images/menu/tawook-sandwich.jpg', null, null, 6, false, 0),
    ('sandwiches', 'Grilled Breast Sandwich', 'سندوتش صدور مشوية', '', '', '100 EGP', '100 ج.م', 'images/menu/grilled-breast-sandwich.jpg', null, null, 7, false, 0),
    ('sandwiches', 'Burger', 'برجر', '', '', '123 EGP', '123 ج.م', 'images/menu/burger.jpg', null, null, 8, false, 0),
    ('sandwiches', 'Liver Sandwich', 'سندوتش كبدة', '', '', '190 EGP', '190 ج.م', 'images/menu/liver-sandwich.jpg', null, null, 9, false, 0),
    ('desserts', 'Rice Pudding', 'أرز باللبن', '', '', '65 EGP', '65 ج.م', 'images/menu/rice-pudding.jpg', null, null, 1, false, 0),
    ('desserts', 'Om Ali', 'أم على', '', '', '85 EGP', '85 ج.م', 'images/menu/om-ali.jpg', null, null, 2, false, 0),
    ('desserts', 'Mahalabia', 'مهلبية', '', '', '65 EGP', '65 ج.م', 'images/menu/mahalabia.jpg', null, null, 3, false, 0),
    ('desserts', 'Crème Caramel', 'كريم كراميل', '', '', '65 EGP', '65 ج.م', 'images/menu/creme-caramel.jpg', null, null, 4, false, 0),
    ('desserts', 'Fruit Salad', 'فروت سلاط', '', '', '85 EGP', '85 ج.م', 'images/menu/fruit-salad.jpg', null, null, 5, false, 0),
    ('desserts', 'Ice Cream', 'ايس كريم', 'Mango, strawberry vanilla, or chocolate', 'مانجو - فراولة فانيليا - شيكولاتة', '90 EGP', '90 ج.م', 'images/menu/ice-cream.jpg', null, null, 6, false, 0),
    ('tajines', 'Tajine Meat with Onions', 'طاجن لحمة بالبصل', '', '', '310 EGP', '310 ج.م', 'images/menu/tajine-meat-with-onions.jpg', null, null, 1, false, 0),
    ('tajines', 'Tajine Potatoes with Meat', 'طاجن بطاطس باللحمة', '', '', '310 EGP', '310 ج.م', 'images/menu/tajine-potatoes-with-meat.jpg', null, null, 2, false, 0),
    ('tajines', 'Tajine Peas with Meat', 'طاجن بسله باللحمة', '', '', '310 EGP', '310 ج.م', 'images/menu/tajine-peas-with-meat.jpg', null, null, 3, false, 0),
    ('tajines', 'Tajine Zucchini Bechamel', 'طاجن كوسة بالبشامل', '', '', '220 EGP', '220 ج.م', 'images/menu/tajine-zucchini-bechamel.jpg', null, null, 4, false, 0),
    ('tajines', 'Tajine Freekeh with Pigeon', 'طاجن فريك بالحمام', '', '', '390 EGP', '390 ج.م', 'images/menu/tajine-freekeh-with-pigeon.jpg', null, null, 5, false, 0),
    ('tajines', 'Plain Stuffed Rice Tajine', 'طاجن أرز معمر سادة', '', '', '130 EGP', '130 ج.م', 'images/menu/plain-stuffed-rice-tajine.jpg', null, null, 6, false, 0),
    ('tajines', 'Plain Molokhia Tajine', 'طاجن ملوخية سادة', '', '', '120 EGP', '120 ج.م', 'images/menu/plain-molokhia-tajine.jpg', null, null, 7, false, 0),
    ('tajines', 'Plain Moussaka Tajine', 'طاجن مسقعة سادة', '', '', '120 EGP', '120 ج.م', 'images/menu/plain-moussaka-tajine.jpg', null, null, 8, false, 0),
    ('tajines', 'Tajine Okra with Lamb', 'طاجن بامية باللحمة الضانى', '', '', '310 EGP', '310 ج.م', 'images/menu/tajine-okra-with-lamb.jpg', null, null, 9, false, 0),
    ('tajines', 'Tajine Mixed Vegetables with Meat', 'طاجن خضار مشكل باللحمة', '', '', '310 EGP', '310 ج.م', 'images/menu/tajine-mixed-vegetables-with-meat.jpg', null, null, 10, false, 0),
    ('tajines', 'Tajine Green Beans with Meat', 'طاجن فاصوليا خضراء باللحمة', '', '', '310 EGP', '310 ج.م', 'images/menu/tajine-green-beans-with-meat.jpg', null, null, 11, false, 0),
    ('tajines', 'Tajine Stuffed Rice with Pigeon', 'طاجن أرز معمر بالحمام', '', '', '410 EGP', '410 ج.م', 'images/menu/tajine-stuffed-rice-with-pigeon.jpg', null, null, 12, false, 0),
    ('tajines', 'Tajine Fattah Kaware', 'طاجن فتة كوارع', '', '', '550 EGP', '550 ج.م', 'images/menu/tajine-fattah-kaware.jpg', null, null, 13, false, 0),
    ('tajines', 'Plain Peas Tajine', 'طاجن بسله سادة', '', '', '120 EGP', '120 ج.م', 'images/menu/plain-peas-tajine.jpg', null, null, 14, false, 0),
    ('tajines', 'Plain Mixed Vegetables Tajine', 'طاجن خضار سادة', '', '', '120 EGP', '120 ج.م', 'images/menu/plain-mixed-vegetables-tajine.jpg', null, null, 15, false, 0),
    ('tajines', 'Plain Potatoes Tajine', 'طاجن بطاطس ساده', '', '', '120 EGP', '120 ج.م', 'images/menu/plain-potatoes-tajine.jpg', null, null, 16, false, 0),
    ('hot-drinks', 'Tea', 'شاى', '', '', '42 EGP', '42 ج.م', 'images/menu/tea.jpg', null, null, 1, false, 0),
    ('hot-drinks', 'Tea Pot', 'براد شاى', '', '', '75 EGP', '75 ج.م', 'images/menu/tea-pot.jpg', null, null, 2, false, 0),
    ('hot-drinks', 'Turkish Coffee', 'قهوة تركى', '', '', '50 EGP', '50 ج.م', 'images/menu/turkish-coffee.jpg', null, null, 3, false, 0),
    ('hot-drinks', 'French Coffee', 'قهوة فرنساوى', '', '', '60 EGP', '60 ج.م', 'images/menu/french-coffee.jpg', null, null, 4, false, 0),
    ('hot-drinks', 'Herbal Tea', 'اعشاب', '', '', '40 EGP', '40 ج.م', 'images/menu/herbal-tea.jpg', null, null, 5, false, 0),
    ('hot-drinks', 'Espresso', 'اسبرسو', '', '', '75 EGP', '75 ج.م', 'images/menu/espresso.jpg', null, null, 6, false, 0),
    ('hot-drinks', 'Cappuccino', 'كابتشينو', 'Hazelnut, caramel, or vanilla', 'بندق / كراميل / فانيليا', '80 EGP', '80 ج.م', 'images/menu/cappuccino.jpg', null, null, 7, false, 0),
    ('hot-drinks', 'Mocha Coffee', 'موكا كافيه', '', '', '80 EGP', '80 ج.م', 'images/menu/mocha-coffee.jpg', null, null, 8, false, 0),
    ('hot-drinks', 'Nescafe', 'نسكافيه', '', '', '65 EGP', '65 ج.م', 'images/menu/nescafe.jpg', null, null, 9, false, 0),
    ('hot-drinks', 'Hot Chocolate', 'هوت شوكلت', '', '', '70 EGP', '70 ج.م', 'images/menu/hot-chocolate.jpg', null, null, 10, false, 0),
    ('hot-drinks', 'Latte', 'لاتيه', '', '', '70 EGP', '70 ج.م', 'images/menu/latte.jpg', null, null, 11, false, 0),
    ('cold-drinks', 'Small Mineral Water', 'مياه معدنيه صغيره', '', '', '28 EGP', '28 ج.م', 'images/menu/small-mineral-water.jpg', null, null, 1, false, 0),
    ('cold-drinks', 'Soft Drink Can', 'كانز', '', '', '41 EGP', '41 ج.م', 'images/menu/soft-drink-can.jpg', null, null, 2, false, 0),
    ('cold-drinks', 'Cola / Diet Cola', 'كولا - كولا دايت', '', '', '41 EGP', '41 ج.م', 'images/menu/cola-diet-cola.jpg', null, null, 3, false, 0),
    ('cold-drinks', 'Sprite / Pineapple', 'اسبريت - اناناس', '', '', '41 EGP', '41 ج.م', 'images/menu/sprite-pineapple.jpg', null, null, 4, false, 0),
    ('cold-drinks', 'Mango Juice', 'عصير مانجو', '', '', '75 EGP', '75 ج.م', 'images/menu/mango-juice.jpg', null, null, 5, false, 0),
    ('cold-drinks', 'Guava Juice', 'عصير جوافة', '', '', '69 EGP', '69 ج.م', 'images/menu/guava-juice.jpg', null, null, 6, false, 0),
    ('cold-drinks', 'Strawberry Juice', 'عصير فراولة', '', '', '69 EGP', '69 ج.م', 'images/menu/strawberry-juice.jpg', null, null, 7, false, 0),
    ('cold-drinks', 'Orange Juice', 'عصير برتقال', '', '', '69 EGP', '69 ج.م', 'images/menu/orange-juice.jpg', null, null, 8, false, 0),
    ('cold-drinks', 'Lemon Juice', 'عصير ليمون', '', '', '69 EGP', '69 ج.م', 'images/menu/lemon-juice.jpg', null, null, 9, false, 0),
    ('cold-drinks', 'Lemon Mint Juice', 'عصير ليمون و نعناع', '', '', '69 EGP', '69 ج.م', 'images/menu/lemon-mint-juice.jpg', null, null, 10, false, 0),
    ('cold-drinks', 'Oreo Shake', 'اوريو تشيك', '', '', '89 EGP', '89 ج.م', 'images/menu/oreo-shake.jpg', null, null, 11, false, 0),
    ('cold-drinks', 'Iced Chocolate', 'ايس شوكلت', '', '', '75 EGP', '75 ج.م', 'images/menu/iced-chocolate.jpg', null, null, 12, false, 0),
    ('cold-drinks', 'Sunshine', 'صن شاين', '', '', '74 EGP', '74 ج.م', 'images/menu/sunshine.jpg', null, null, 13, false, 0),
    ('cold-drinks', 'Cherry Cola', 'شيرى كولا', '', '', '65 EGP', '65 ج.م', 'images/menu/cherry-cola.jpg', null, null, 14, false, 0),
    ('cold-drinks', 'Smoothie', 'سموزى', 'Mango, strawberry, or berries', 'مانجو / فراولة / توت', '80 EGP', '80 ج.م', 'images/menu/smoothie.jpg', null, null, 15, false, 0),
    ('cold-drinks', 'Berry Mix', 'ميكس توت', 'Peach, lemon, or mint', 'خوخ / ليمون / نعناع', '80 EGP', '80 ج.م', 'images/menu/berry-mix.jpg', null, null, 16, false, 0),
    ('cold-drinks', 'Milkshake', 'ميلك تشيك', 'Mango, strawberry, vanilla, or chocolate', 'مانجو / فراولة / فانيليا / شيكولاته', '80 EGP', '80 ج.م', 'images/menu/milkshake.jpg', null, null, 17, false, 0),
    ('grills', 'Kofta (¼ kg)', 'كفتة (ربع كيلو)', '', '', '297.50 EGP', '297.50 ج.م', 'images/menu/kofta.jpg', null, null, 1, false, 0),
    ('grills', 'Kofta (⅓ kg)', 'كفتة (ثلث كيلو)', '', '', '446.25 EGP', '446.25 ج.م', 'images/menu/kofta.jpg', null, null, 2, false, 0),
    ('grills', 'Kofta (1 kg)', 'كفتة (كيلو)', '', '', '1190 EGP', '1190 ج.م', 'images/menu/kofta.jpg', null, null, 3, true, 3),
    ('grills', 'Tarb (¼ kg)', 'طرب (ربع كيلو)', '', '', '297.50 EGP', '297.50 ج.م', 'images/menu/tarb.jpg', null, null, 4, false, 0),
    ('grills', 'Tarb (⅓ kg)', 'طرب (ثلث كيلو)', '', '', '446.25 EGP', '446.25 ج.م', 'images/menu/tarb.jpg', null, null, 5, false, 0),
    ('grills', 'Tarb (1 kg)', 'طرب (كيلو)', '', '', '1190 EGP', '1190 ج.م', 'images/menu/tarb.jpg', null, null, 6, false, 0),
    ('grills', 'Veal Kebab (¼ kg)', 'كباب بتلو (ربع كيلو)', '', '', '395 EGP', '395 ج.م', 'images/menu/veal-kebab.jpg', null, null, 7, false, 0),
    ('grills', 'Veal Kebab (⅓ kg)', 'كباب بتلو (ثلث كيلو)', '', '', '592.50 EGP', '592.50 ج.م', 'images/menu/veal-kebab.jpg', null, null, 8, false, 0),
    ('grills', 'Veal Kebab (1 kg)', 'كباب بتلو (كيلو)', '', '', '1580 EGP', '1580 ج.م', 'images/menu/veal-kebab.jpg', null, null, 9, false, 0),
    ('grills', 'Veal Ribs (⅓ kg)', 'ريش بتلو (ثلث كيلو)', '', '', '630.50 EGP', '630.50 ج.م', 'images/menu/veal-ribs.jpg', null, null, 10, false, 0),
    ('grills', 'Veal Ribs (1 kg)', 'ريش بتلو (كيلو)', '', '', '1680 EGP', '1680 ج.م', 'images/menu/veal-ribs.jpg', null, null, 11, false, 0),
    ('grills', 'Veal Liver (¼ kg)', 'كبده بتلو (ربع كيلو)', '', '', '375 EGP', '375 ج.م', 'images/menu/veal-liver.jpg', null, null, 12, false, 0),
    ('grills', 'Veal Liver (⅓ kg)', 'كبده بتلو (ثلث كيلو)', '', '', '562.50 EGP', '562.50 ج.م', 'images/menu/veal-liver.jpg', null, null, 13, false, 0),
    ('grills', 'Veal Liver (1 kg)', 'كبده بتلو (كيلو)', '', '', '1500 EGP', '1500 ج.م', 'images/menu/veal-liver.jpg', null, null, 14, false, 0),
    ('grills', 'Lamb Kebab (¼ kg)', 'كباب ضانى (ربع كيلو)', '', '', '395 EGP', '395 ج.م', 'images/menu/lamb-kebab.jpg', null, null, 15, false, 0),
    ('grills', 'Lamb Kebab (⅓ kg)', 'كباب ضانى (ثلث كيلو)', '', '', '592.50 EGP', '592.50 ج.م', 'images/menu/lamb-kebab.jpg', null, null, 16, false, 0),
    ('grills', 'Lamb Kebab (1 kg)', 'كباب ضانى (كيلو)', '', '', '1580 EGP', '1580 ج.م', 'images/menu/lamb-kebab.jpg', null, null, 17, false, 0),
    ('grills', 'Lamb Kebab and Kofta (¼ kg)', 'كباب و كفتة ضانى (ربع كيلو)', '', '', '346.25 EGP', '346.25 ج.م', 'images/menu/lamb-kebab-and-kofta.jpg', null, null, 18, false, 0),
    ('grills', 'Lamb Kebab and Kofta (⅓ kg)', 'كباب و كفتة ضانى (ثلث كيلو)', '', '', '520.50 EGP', '520.50 ج.م', 'images/menu/lamb-kebab-and-kofta.jpg', null, null, 19, false, 0),
    ('grills', 'Lamb Kebab and Kofta (1 kg)', 'كباب و كفتة ضانى (كيلو)', '', '', '1385 EGP', '1385 ج.م', 'images/menu/lamb-kebab-and-kofta.jpg', null, null, 20, false, 0),
    ('grills', 'Veal Kebab and Kofta (¼ kg)', 'كباب و كفتة بتلو (ربع كيلو)', '', '', '346.25 EGP', '346.25 ج.م', 'images/menu/veal-kebab-and-kofta.jpg', null, null, 21, false, 0),
    ('grills', 'Veal Kebab and Kofta (⅓ kg)', 'كباب و كفتة بتلو (ثلث كيلو)', '', '', '520.50 EGP', '520.50 ج.م', 'images/menu/veal-kebab-and-kofta.jpg', null, null, 22, false, 0),
    ('grills', 'Veal Kebab and Kofta (1 kg)', 'كباب و كفتة بتلو (كيلو)', '', '', '1385 EGP', '1385 ج.م', 'images/menu/veal-kebab-and-kofta.jpg', null, null, 23, false, 0),
    ('grills', 'Lamb Ribs (¼ kg)', 'ريش ضانى (ربع كيلو)', '', '', '420 EGP', '420 ج.م', 'images/menu/lamb-ribs.jpg', null, null, 24, false, 0),
    ('grills', 'Lamb Ribs (⅓ kg)', 'ريش ضانى (ثلث كيلو)', '', '', '630.50 EGP', '630.50 ج.م', 'images/menu/lamb-ribs.jpg', null, null, 25, false, 0),
    ('grills', 'Lamb Ribs (1 kg)', 'ريش ضانى (كيلو)', '', '', '1680 EGP', '1680 ج.م', 'images/menu/lamb-ribs.jpg', null, null, 26, true, 4),
    ('grills', 'Lamb Fillet (¼ kg)', 'فلتو ضانى (ربع كيلو)', '', '', '420 EGP', '420 ج.م', 'images/menu/lamb-fillet.jpg', null, null, 27, false, 0),
    ('grills', 'Lamb Fillet (⅓ kg)', 'فلتو ضانى (ثلث كيلو)', '', '', '630.50 EGP', '630.50 ج.م', 'images/menu/lamb-fillet.jpg', null, null, 28, false, 0),
    ('grills', 'Lamb Fillet (1 kg)', 'فلتو ضانى (كيلو)', '', '', '1680 EGP', '1680 ج.م', 'images/menu/lamb-fillet.jpg', null, null, 29, false, 0),
    ('grills', 'Sausage (¼ kg)', 'سجق (ربع كيلو)', '', '', '297.50 EGP', '297.50 ج.م', 'images/menu/sausage.jpg', null, null, 30, false, 0),
    ('grills', 'Sausage (⅓ kg)', 'سجق (ثلث كيلو)', '', '', '446.25 EGP', '446.25 ج.م', 'images/menu/sausage.jpg', null, null, 31, false, 0),
    ('grills', 'Sausage (1 kg)', 'سجق (كيلو)', '', '', '1190 EGP', '1190 ج.م', 'images/menu/sausage.jpg', null, null, 32, false, 0),
    ('grills', 'Beef Fillet Kandooz (⅓ kg)', 'فيلية كندوز (ثلث كيلو)', '', '', '562 EGP', '562 ج.م', 'images/menu/beef-fillet-kandooz.jpg', null, null, 33, false, 0),
    ('grills', 'Beef Fillet Kandooz (1 kg)', 'فيلية كندوز (كيلو)', '', '', '1500 EGP', '1500 ج.م', 'images/menu/beef-fillet-kandooz.jpg', null, null, 34, false, 0),
    ('grills', 'Shish Tawook (¼ kg)', 'شيش طاووق (ربع كيلو)', '', '', '190 EGP', '190 ج.م', 'images/menu/shish-tawook.jpg', null, null, 35, false, 0),
    ('grills', 'Shish Tawook (⅓ kg)', 'شيش طاووق (ثلث كيلو)', '', '', '285 EGP', '285 ج.م', 'images/menu/shish-tawook.jpg', null, null, 36, false, 0),
    ('grills', 'Shish Tawook (1 kg)', 'شيش طاووق (كيلو)', '', '', '760 EGP', '760 ج.م', 'images/menu/shish-tawook.jpg', null, null, 37, true, 5),
    ('grills', 'Grilled Chicken Breasts (¼ kg)', 'صدور مشوية (ربع كيلو)', '', '', '195 EGP', '195 ج.م', 'images/menu/grilled-chicken-breasts.jpg', null, null, 38, false, 0),
    ('grills', 'Grilled Chicken Breasts (⅓ kg)', 'صدور مشوية (ثلث كيلو)', '', '', '292.75 EGP', '292.75 ج.م', 'images/menu/grilled-chicken-breasts.jpg', null, null, 39, false, 0),
    ('grills', 'Grilled Chicken Breasts (1 kg)', 'صدور مشوية (كيلو)', '', '', '780 EGP', '780 ج.م', 'images/menu/grilled-chicken-breasts.jpg', null, null, 40, false, 0),
    ('grills', 'Grilled Lamb Shank', 'موزة ضانى مشوية', '', '', '600 EGP', '600 ج.م', 'images/menu/grilled-lamb-shank.jpg', null, null, 41, false, 0),
    ('grills', 'Grilled Veal Shank', 'موزة بتلو مشوية', '', '', '620 EGP', '620 ج.م', 'images/menu/grilled-veal-shank.jpg', null, null, 42, false, 0),
    ('grills', 'Grilled Whole Chicken', 'فرخة مشوية', '', '', '380 EGP', '380 ج.م', 'images/menu/grilled-whole-chicken.jpg', null, null, 43, false, 0),
    ('grills', 'Boneless Grilled Chicken', 'فرخة مخلية', '', '', '460 EGP', '460 ج.م', 'images/menu/boneless-grilled-chicken.jpg', null, null, 44, false, 0),
    ('grills', 'Shish Grilled Chicken', 'فرخة شيش', '', '', '380 EGP', '380 ج.م', 'images/menu/shish-grilled-chicken.jpg', null, null, 45, false, 0),
    ('grills', 'Hawawshi', 'حواوشي', '', '', '170 EGP', '170 ج.م', 'images/menu/hawawshi.jpg', null, null, 46, false, 0),
    ('grills', 'Pair of Quails', 'جوز سمان', '', '', '320 EGP', '320 ج.م', 'images/menu/pair-of-quails.jpg', null, null, 47, false, 0),
    ('grills', 'Stuffed Pigeon Rice or Freekeh', 'فرد حمام محشى (أرز - فريك)', '', '', '230 EGP', '230 ج.م', 'images/menu/stuffed-pigeon-rice-or-freekeh.jpg', null, null, 48, false, 0)
  ) as v(
  slug,
  name_en,
  name_ar,
  description_en,
  description_ar,
  price_en,
  price_ar,
  image_url,
  badge_en,
  badge_ar,
  sort_order,
  is_signature,
  signature_sort_order
)
join public.categories c
  on c.slug = v.slug
 and c.is_deleted = false;
